---
- name: Install Docker
  block:
    - name: Iinstall addidtion packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        update-cache: yes
           
    - name: Add folder
      file:
        path: /etc/apt/keyrings
        state: directory
        
    - name: Add Docker key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
        keyring: /etc/apt/keyrings/docker.gpg

    - name: Add repo
      apt_repository:
        repo: >
          deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] 
          https://download.docker.com/linux/debian
          {{ ansible_distribution_release }} stable
        state: present
        update-cache: yes
        filename: docker

    - name: Install Docker-ce
      apt: 
        name: docker-ce
        update-cache: yes
    
    - name: Verify that Docker is installed
      service:
        name: docker
        state: restarted
        enabled: yes
  become: yes

- name: Installing Docker-compose
  block:
  - name: Get latest version
    uri:
      url: https://api.github.com/repos/docker/compose/releases/latest
      body_format: json
    register: page

  - name: install DC
    get_url:
      url: "https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-Linux-x86_64"
      dest: /usr/local/bin/docker-compose
      mode: 0755
  become: true

- name: finish
  block:
  - name: Add user to group
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes
  become: yes  
  tags: preconf